name: EssentialsNK
version: "1.0.3"
api: ["1.0.0"]
author: Scallop
description: EssentialsNK
main: cn.yescallop.essentialsnk.EssentialsNK

permissions:
 essentialsnk.back:
  default: true
 essentialsnk.break:
  default: op
 essentialsnk.broadcast:
  default: op
 essentialsnk.burn:
  default: op
 essentialsnk.clearinventory:
  default: op
 essentialsnk.clearinventory.other:
  default: op
 essentialsnk.compass:
  default: true
 essentialsnk.delhome:
  default: true
 essentialsnk.delwarp:
  default: op
 essentialsnk.depth:
  default: true
 essentialsnk.extinguish:
  default: op
 essentialsnk.extinguish.other:
  default: op
 essentialsnk.feed:
  default: op
 essentialsnk.feed.other:
  default: op
 essentialsnk.fly:
  default: op
 essentialsnk.fly.other:
  default: op
 essentialsnk.gamemode:
  default: op
 essentialsnk.getpos:
  default: true
 essentialsnk.getpos.other:
  default: op
 essentialsnk.heal:
  default: op
 essentialsnk.heal.other:
  default: op
 essentialsnk.home:
  default: true
 essentialsnk.itemdb:
  default: true
 essentialsnk.jump:
  default: op
 essentialsnk.kickall:
  default: op
 essentialsnk.lightning:
  default: op
 essentialsnk.more:
  default: op
 essentialsnk.ping:
  default: true
 essentialsnk.repair:
  default: op
 essentialsnk.repair.all:
  default: op
 essentialsnk.repair.armor:
  default: op
 essentialsnk.sethome:
  default: true
 essentialsnk.setwarp:
  default: op
 essentialsnk.tpa:
  default: true
 essentialsnk.tpaall:
  default: op
 essentialsnk.tpaccept:
  default: true
 essentialsnk.tpahere:
  default: true
 essentialsnk.tpall:
  default: true
 essentialsnk.tpdeny:
  default: true
 essentialsnk.tphere:
  default: op
 essentialsnk.vanish:
  default: op
 essentialsnk.vanish.other:
  default: op
 essentialsnk.warp:
  default: true
 essentialsnk.warp.other:
  default: op
 essentialsnk.world:
  default: true
